### ISSUE TITLE
txn vs jti vs none

### ISSUE THREAD

**Issue by dhs-aws** [ietf-scim-wg/draft-ietf-scim-events#15]
In the definition for `txn` it is stated, "if not provided, the SET `jti` claim may be used."  As I read this it does not appear that either are required, which could lead to a state where duplicate transactions are received and acted upon.

Should the definition require either `txn`, `jti`, or both?

**Comment by independentid** [comment]
﻿I tend to agree that txn should be required. Also it is possible that multiple sets can have same txn if publisher chooses to issue separate sets for the same txn. Eg. Authentication factor change and prov change indicating attribute changes. Other case is async bulk response. PhilPhilOn Nov 27, 2023, at 10:16 AM, Dean H. Saxe - AWS Identity ***@***.***> wrote:﻿
In the definition for txn it is stated, "if not provided, the SET jti claim may be used."  As I read this it does not appear that either are required, which could lead to a state where duplicate transactions are received and acted upon.
Should the definition require either txn, jti, or both?

**Comment by dhs-aws** [comment]
See PR #29 for suggested verbiage.
