### ISSUE TITLE
hard vs. soft delete vs. activation - Section 2.4.5

### ISSUE THREAD

**Issue by dhs-aws** [ietf-scim-wg/draft-ietf-scim-events#18]
SCIM does not define hard vs. soft deletion today.  This draft includes language in 2.4.5 that indicates whether a user (or in general, a resource) has been activated or not.  I can find no terminology in 7642/7643/7644 corresponding to the idea of "activation".  This strikes me as an issue of soft vs. hard deletion or a business-specific attribute on resources, such as a new hire that may not be "activated" until their Day 1.  Further, this section goes on to indicate that the event published and receiver have to agreed upon the usage of this activate message, leading to non-normative deployments with different business specific rules around this attribute of a resource.  

I request that this is removed from the draft until such a time as the SCIM protocol defines hard/soft deletion rules and/or the concept of activation is implemented by specification.  My concern is that as it is written today, it is too loose to be effectively used by providers and clients, and may lead to further confusion around the issue of deleted resources.

@ansg-aws do you have additional feedback on hard/soft delete?  I know you've been considering this based on our 1:1 conversations.

**Comment by independentid** [comment]
﻿﻿﻿DeanThis has nothing to do with hard or soft delete.  This refers to whether the account status is active (ie the attribute active).  An account can be marked active = false and still be available as a resource. active
      A Boolean value indicating the user's administrative status.  The
      definitive meaning of this attribute is determined by the service
      provider.  As a typical example, a value of true implies that the
      user is able to log in, while a value of false implies that the
      user's account has been suspended.PhilOn Nov 27, 2023, at 10:27 AM, Dean H. Saxe - AWS Identity ***@***.***> wrote:﻿
SCIM does not define hard vs. soft deletion today.  This draft includes language in 2.4.5 that indicates whether a user (or in general, a resource) has been activated or not.  I can find no terminology in 7642/7643/7644 corresponding to the idea of "activation".  This strikes me as an issue of soft vs. hard deletion or a business-specific attribute on resources, such as a new hire that may not be "activated" until their Day 1.  Further, this section goes on to indicate that the event published and receiver have to agreed upon the usage of this activate message, leading to non-normative deployments with different business specific rules around this attribute of a resource.
I request that this is removed from the draft until such a time as the SCIM protocol defines hard/soft deletion rules and/or the concept of activation is implemented by specification.  My concern is that as it is written today, it is too loose to be effectively used by providers and clients, and may lead to further confusion around the issue of deleted resources.
@ansg-aws do you have additional feedback on hard/soft delete?  I know you've been considering this based on our 1:1 conversations.

**Comment by independentid** [comment]
﻿﻿﻿﻿DeanThis has nothing to do with hard or soft delete.  This refers to whether the account status is active (ie the attribute active).  An account can be marked active = false and still be available as a resource. active
      A Boolean value indicating the user's administrative status.  The
      definitive meaning of this attribute is determined by the service
      provider.  As a typical example, a value of true implies that the
      user is able to log in, while a value of false implies that the
      user's account has been suspended.PhilOn Nov 27, 2023, at 10:27 AM, Dean H. Saxe - AWS Identity ***@***.***> wrote:﻿
SCIM does not define hard vs. soft deletion today.  This draft includes language in 2.4.5 that indicates whether a user (or in general, a resource) has been activated or not.  I can find no terminology in 7642/7643/7644 corresponding to the idea of "activation".  This strikes me as an issue of soft vs. hard deletion or a business-specific attribute on resources, such as a new hire that may not be "activated" until their Day 1.  Further, this section goes on to indicate that the event published and receiver have to agreed upon the usage of this activate message, leading to non-normative deployments with different business specific rules around this attribute of a resource.
I request that this is removed from the draft until such a time as the SCIM protocol defines hard/soft deletion rules and/or the concept of activation is implemented by specification.  My concern is that as it is written today, it is too loose to be effectively used by providers and clients, and may lead to further confusion around the issue of deleted resources.
@ansg-aws do you have additional feedback on hard/soft delete?  I know you've been considering this based on our 1:1 conversations.

**Comment by dhs-aws** [comment]
Thanks for clarifying that it is not related to hard/soft delete.  If that's the case, I think this should be removed as it doesn't describe any known set of attributes about a resource in SCIM.

**Comment by jischr** [comment]
this is a great issue. active property is on user resource schema, if another resource schema was used as a base, could unnecessarily confuse?

**Comment by dhs-aws** [comment]
I'll also add that RISC covers account enablement/disablement. This may be a case where deferring to the RISC profile is sufficient.

https://openid.net/specs/openid-risc-profile-specification-1_0.html#account-disabled

**Comment by independentid** [comment]
I believe this issue is closed. If desired please discuss on the mailing list.  From my perspective "active" is really a SCIM systems way of say'ing we're ready from a provisioning perspective.  It may be, but not always, similar to RISC.
