### ISSUE TITLE
Consider removal of non-normaitve guidance in 3.2

### ISSUE THREAD

**Issue by dhs-aws** [ietf-scim-wg/draft-ietf-scim-events#22]
Section 3.2 Point-to-Point Delivery over HTTP goes into detail over the HTTP delivery methods, describing push and pull mechanisms and their relative advantages and disadvantages.  Reading the guidance, I find that it is not necessary in the specification. Further, it makes unsupported claims regarding networking policy changes which do not reflect the current state of deployed systems.  Notably, "Systems behind protected network boundaries can reach externally hosted systems without requiring special firewall or network configuration" is false.  Many services are deployed with limited or no egress unless it is explicitly required and configured to support the use case.  

I recommend deletion of the entire section.

**Comment by jischr** [comment]
if we want to include any, id trim it down to one paragraph and refer to the SET RFC 8417

**Comment by independentid** [comment]
Section 3 from Draft 03 was removed in Draft 04.
