### ISSUE TITLE
Security Considerations - Throttling

### ISSUE THREAD

**Issue by dhs-aws** [ietf-scim-wg/draft-ietf-scim-events#24]
The description of throttling in the security considerations does not give any mechanism for the client to discover any throttling that may be in place.  When this is combined with the description of SET Patch events happening at a rapid pace, and the server decides to issue a consolidated change, this may not meet the needs of the receiver.  Receivers, due to policy, regulation, or law, may need to know every change that has happened when it occurs.  This type of throttling to consolidate changes may be insufficient.

I strongly recommend removing this section.  However, there is utility in the design and I suggest that this throttling be added in a future SCIM profile or within this document as a recommended practice iff the client can discover that such throttling is occurring and disable such throttling, if desired.

**Comment by independentid** [comment]
I re-read the paragraph:
```
   In operation, some SCIM resources such as SCIM Groups may have a high
   rate of change.  Implementors and operators SHOULD consider use of
   throttling techniques to balance immediacy and frequency.  For
   example, a large group whose members change dozens of times per
   second may not need discrete SET Patch Events per change.  Instead,
   issuing a single consolidated change per second or even minute may be
   beneficial to keeping Event Receivers up-to-date.  Likewise, a Co-
   ordinated Provisioning Event Receiver (Section 2.2), does not
   necessarily need to retrieve the full Group on every change request.
   It MAY choose to do lookups on a less frequent scale for
   reconciliation.
```

The point of the paragraph is to alert implementers of the unique problems posed by large groups that could generate a large number of events.   From an interop perspective, it makes no difference to the client as the consolidating change should be the equivalent.   

The problem is that many clients could be overwhelmed.  We're not saying anything normative here. We are just alerting parties to the consideration.

**Comment by dhs-aws** [comment]
I understand this is not normative guidance, but it does leave open the possibility of implementers of clients and servers having different understandings of the state of the object on the server.  I won't block on this, but I would prefer that additional verbiage is added to address the risk of inconsistent state on server and client in this scenario.

**Comment by independentid** [comment]
I don't see how consolidating events would lead to an inconsistency with regards to groups.  Maybe the term "throttling" itself should be changed?

**Comment by independentid** [comment]
IOW. The intent is not to throttle by loosing information. The intent is to reduce risk of loss by reducing group update frequency by consolidating multiple transactions into a single event.  E.g. don't be issuing 1000s of events per second. issue a consolidated event per second (or minute)

**Comment by dhs-aws** [comment]
I get it - I don't think there's any data fidelity loss on the server.  But for orgs who need to know that the returned state is exactly the state at that point in time, such as to prove compliance, the client should be aware that the server may throttle the events during periods of rapid changes.  

At a minimum, it should be identified as a server property so that clients know to expect it, if there's not a way to disable it entirely.

**Comment by independentid** [comment]
I think I am missing your point. How is it informationally different to the client? The difference is how best to keep the receiver as up to date as possible. Without consolidation a receiver may fall further behind than having to wait a second for a single larger event. PhilOn Apr 9, 2024, at 4:02 PM, Dean H. Saxe - AWS Identity ***@***.***> wrote:﻿
I get it - I don't think there's any data fidelity loss on the server.  But for orgs who need to know that the returned state is exactly the state at that point in time, such as to prove compliance, the client should be aware that the server may throttle the events during periods of rapid changes.
At a minimum, it should be identified as a server property so that clients know to expect it, if there's not a way to disable it entirely.

**Comment by independentid** [comment]
How about this:

```
In practice, SCIM resources with extremely large attribute values such as SCIM Groups, may have a high rate of change 
(e.g. groups with > 100K member values). This could lead to excessive generation of change events causing Event Receivers to fall behind. Implementors SHOULD
consider the impact of high event rates on receivers. SCIM Event Publishers might consider the following:
* Convert SCIM PUT events into describing only changed information by converting to SCIM Patch Events (to keep event size small)
* Combine multiple PATCH requests into an information equivalent SCIM Patch Event. This trades off issuing an exact record of changes to ensuring timely processing at event receivers.
* Use SCIM Patch "notice" events, to trigger Event receivers to do a follow-up SCIM GET on the resource to retrieve exact state of the resource at a time of the event receiver's choosing.
```

**Comment by independentid** [comment]
Changed to:
```
   In operation, some SCIM resources such as SCIM Groups may have a high
   rate of change such a groups with more than 100k member values.  This
   could lead to an excessive event rate that SHOULD be considered by
   Event Publishers and Receivers.  Consider the following to help
   mitigate throughput issues:

   *  Avoid use of SCIM PUT (section 3.5.1 [RFC7644] operations on large
      groups as this may require excessive locking in data store systems
      as well as large Security Event payloads.  Use SCIM PATCH (section
      3.5.2) to focus on updating and notifying about changed
      information.

   *  Use Patch Notice (urn:ietf:params:SCIM:event:prov:patch:notice) to
      reduce event content combined with using periodic SCIM GET (see
      section 3.4 [RFC7644]) to retrieve current group state

   *  Aggregate multiple PATCH Events into a single event providing the
      exact date of each membership change is not critical but that the
      information content remains intact.
```
