### ISSUE TITLE
Relative path in sub_id.urn while absolute paths are common

### ISSUE THREAD

**Issue by arietimmerman** [ietf-scim-wg/draft-ietf-scim-events#30]
It is specified that `sub_id.urn` must contain the relative path for the resource. I wonder why, since the SCIM protocol uses absolute paths in `meta.location`. To me it makes more sense to include absolutes path in `sub_id.urn` as well.

https://github.com/ietf-scim-wg/draft-ietf-scim-events/blob/a6919a3feb10ea5d0784578225f7bf6386908dbf/draft-ietf-scim-events-04.xml#L286C27-L286C27

**Comment by independentid** [comment]
Arie,

The same event may be sent to more than one receiver (multiple audiences). Each receiver may have a unique URL for the SCIM service (RFC7644) access. Using relative allows the event to be sent to multiple receivers.

Phil
***@***.***
