### ISSUE TITLE
Specify the syntax allowed for `attributes` attribute

### ISSUE THREAD

**Issue by gisle** [ietf-scim-wg/draft-ietf-scim-events#35]
Suggested addition to the description of the [`attributes` attribute](https://github.com/ietf-scim-wg/draft-ietf-scim-events/blob/685e0963e517dc09efd4f006721987b4c0b5afa1/draft-ietf-scim-events-04.txt#L406C1-L409C42):

> The attribute values should conform to the ABNF syntax rule for `PATH`  from [RFC7644 section 3.5.2](https://datatracker.ietf.org/doc/html/rfc7644#section-3.5.2).

**Comment by independentid** [comment]
Added. Thanks
